[pytest]
addopts = --import-mode=importlib
testpaths =
    car_control_A/tests
    car_control_B/tests
    car_control_B2/tests
    car_control_C/tests
    car_control_D/tests
    integration/tests
python_files = test_*.py
python_classes = Test*
